"""empty message

Revision ID: 05b906417e42
Revises: None
Create Date: 2017-01-04 16:14:26.937552

"""

# revision identifiers, used by Alembic.
revision = '05b906417e42'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('result_all', postgresql.JSON, nullable=True),
    sa.Column('result_no_stop_words', postgresql.JSON, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###
